services:
  nginx:
    build:
      context: .
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/stream.d:/etc/nginx/stream.d:ro
      - ./nginx/ech:/etc/nginx/ech:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./nginx/logs:/var/log/nginx:rw
      - ./static:/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /run/website:/run/website
