# Proxy
upstream mail_backend {
    server 100.86.39.5:8080;
}

upstream website_backend {
    server unix:/run/website/app.sock;
}

map $host $backend {
    ~^mail\.infra\.  mail_backend;
    default          website_backend;
}

# Redirect
map $host $redirect_host {
    ~^(?<sub>.+)\.(?:diamondgotcat\.net|d-g-c\.net|nerc1\.dev)$  $sub.nercone.dev;
    ~^(?:diamondgotcat\.net|d-g-c\.net|nerc1\.dev)$              nercone.dev;
    default  "";
}

# Other, Plaintext
server {
    listen 80;
    listen [::]:80;
    server_name *.nerc1.dev *.diamondgotcat.net *.d-g-c.net
                  nerc1.dev   diamondgotcat.net   d-g-c.net;
    return 301 https://$redirect_host$request_uri;
}

# Other, TLS
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;
    server_name *.nerc1.dev *.diamondgotcat.net *.d-g-c.net
                  nerc1.dev   diamondgotcat.net   d-g-c.net;

    include /etc/nginx/snippets/ssl.conf;

    return 301 https://$redirect_host$request_uri;
}

# nercone.dev, Plaintext
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name *.nercone.dev nercone.dev;
    return 301 https://$host$request_uri;
}

# nercone.dev, TLS
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    listen 443 quic reuseport;
    listen [::]:443 quic reuseport;
    http2 on;
    server_name *.nercone.dev nercone.dev;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/error.conf;

    location / {
        proxy_pass http://$backend;
        include /etc/nginx/snippets/proxy.conf;
    }
}
