upstream mail_backend {
    server localhost:8081;
}

upstream website_backend {
    server unix:/run/website/app.sock;
}

map $host $backend {
    ~^mail\.infra\.  mail_backend;
    default          website_backend;
}

map $host $redirect_host {
    ~^(?<sub>.+)\.(?:diamondgotcat\.net|d-g-c\.net|nerc1\.dev)$  $sub.nercone.dev;
    ~^(?:diamondgotcat\.net|d-g-c\.net|nerc1\.dev)$              nercone.dev;
    default  "";
}

server {
    listen 80;
    listen [::]:80;
    server_name *.nercone.dev nercone.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name *.nerc1.dev *.diamondgotcat.net *.d-g-c.net
                  nerc1.dev   diamondgotcat.net   d-g-c.net;
    return 301 https://$redirect_host$request_uri;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name *.nerconexssicpt442ngh5lt7hwyh47sk3rob3iei263s7lcjann633id.onion
                  nerconexssicpt442ngh5lt7hwyh47sk3rob3iei263s7lcjann633id.onion
                *.4sbb7xhdn4meuesnqvcreewk6sjnvchrsx4lpnxmnjhz2soat74finid.onion
                  4sbb7xhdn4meuesnqvcreewk6sjnvchrsx4lpnxmnjhz2soat74finid.onion;

    include /etc/nginx/snippets/error.conf;

    location / {
        proxy_pass http://$backend;
        include /etc/nginx/snippets/proxy.conf;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;
    server_name *.nerc1.dev *.diamondgotcat.net *.d-g-c.net
                  nerc1.dev   diamondgotcat.net   d-g-c.net;

    include /etc/nginx/snippets/ssl.conf;

    return 301 https://$redirect_host$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    listen 443 quic reuseport;
    listen [::]:443 quic reuseport;
    http2 on;
    server_name *.nercone.dev *.nerconexssicpt442ngh5lt7hwyh47sk3rob3iei263s7lcjann633id.onion *.4sbb7xhdn4meuesnqvcreewk6sjnvchrsx4lpnxmnjhz2soat74finid.onion
                  nercone.dev   nerconexssicpt442ngh5lt7hwyh47sk3rob3iei263s7lcjann633id.onion   4sbb7xhdn4meuesnqvcreewk6sjnvchrsx4lpnxmnjhz2soat74finid.onion;

    include /etc/nginx/snippets/ssl.conf;
    include /etc/nginx/snippets/error.conf;

    location / {
        proxy_pass http://$backend;
        include /etc/nginx/snippets/proxy.conf;
    }
}
